# architect: false
# o1-preview: true
# editor-model: "claude-3-5-sonnet-20241022"
sonnet: true

# model: "openai/deepseek-v2.5"
# openai-api-base: "https://inf.33ca82-shanks.coreweave.app/ollama/v1"
dark-mode: true

# Enable watching files for AI coding comments
watch-files: true

# Disable aider in commits
attribute-author: false
attribute-committer: false
