- name: github/o3
  streaming: false
  edit_format: diff
  weak_model_name: github/gpt-4.1-mini
  use_repo_map: true
  use_temperature: false
  editor_model_name: github/gpt-4.1
  editor_edit_format: editor-diff
  system_prompt_prefix: "Formatting re-enabled. "
  accepts_settings: ["reasoning_effort"]
  examples_as_sys_msg: true

- name: github/o4-mini
  edit_format: diff
  weak_model_name: github/gpt-4.1-mini
  use_repo_map: true
  use_temperature: false
  editor_model_name: github/gpt-4.1
  editor_edit_format: editor-diff
  system_prompt_prefix: "Formatting re-enabled. "
  accepts_settings: ["reasoning_effort"]
  examples_as_sys_msg: true

- name: github/gpt-4.1
  edit_format: diff
  weak_model_name: github/gpt-4.1-mini
  use_repo_map: true
  reminder: sys
  examples_as_sys_msg: false
  editor_model_name: github/gpt-4.1-mini

- name: github/gpt-4.1-mini
  edit_format: diff
  use_repo_map: true
  reminder: sys
  examples_as_sys_msg: false

# Use openai provider for openai-compatible API server
- name: openai/qwen3:30b-a3b
  edit_format: diff
  use_repo_map: true
  overeager: true
  examples_as_sys_msg: true
  reasoning_tag: think
