alias:
  - "gemini:gemini/gemini-2.5-pro-exp-03-25"
model: "github/gpt-4.1"

dark-mode: true
check-update: false
yes-always: true
suggest-shell-commands: false
detect-urls: false
vim: true
restore-chat-history: true
max-chat-history-tokens: 2000

# Always keep file tree map small to keep context focused.
# https://aider.chat/docs/troubleshooting/edit-errors.html
map-tokens: 1000

# Enable watching files for AI coding comments
watch-files: true

# Disable aider in commits
attribute-author: false
attribute-committer: false

commit-prompt: |
  You are an expert software engineer that generates concise, \
  one-line Git commit messages based on the provided diffs.
  Review the provided context and diffs which are about to be committed to a git repo.
  Review the diffs carefully.
  Generate a one-line commit message for those changes.

  Ensure the commit message:
  - Is in the imperative mood (e.g., \"Add feature\" not \"Added feature\" or \"Adding feature\").
  - Does not exceed 72 characters.

  Reply only with the one-line commit message, without any additional text, explanations, \
  or line breaks.
