- name: github/o3
  streaming: false
  edit_format: diff
  weak_model_name: github/gpt-4.1-mini
  use_repo_map: true
  use_temperature: false
  editor_model_name: github/gpt-4.1
  editor_edit_format: editor-diff
  system_prompt_prefix: "Formatting re-enabled. "
  accepts_settings: ["reasoning_effort"]
  examples_as_sys_msg: true

- name: github/o4-mini
  edit_format: diff
  weak_model_name: github/gpt-4.1-mini
  use_repo_map: true
  use_temperature: false
  editor_model_name: github/gpt-4.1
  editor_edit_format: editor-diff
  system_prompt_prefix: "Formatting re-enabled. "
  accepts_settings: ["reasoning_effort"]
  examples_as_sys_msg: true

- name: github/gpt-4.1
  edit_format: diff
  weak_model_name: github/gpt-4.1-mini
  use_repo_map: true
  reminder: sys
  examples_as_sys_msg: false
  editor_model_name: github/gpt-4.1-mini

- name: github/gpt-4.1-mini
  edit_format: diff
  use_repo_map: true
  reminder: sys
  examples_as_sys_msg: false

# Use openai provider for openai-compatible API server
- name: openai/qwen3:30b-a3b
  weak_model_name: openai/qwen3:30b-a3b-no-think
  edit_format: diff
  use_repo_map: true
  overeager: false
  examples_as_sys_msg: true
  extra_params:
    extra_headers:
      Model: Qwen/Qwen3-30B-A3B-FP8
    temperature: 0.6
    top_p: 0.95
    top_k: 20
    presence_penalty: 1.5

- name: openai/qwen3:30b-a3b-no-think
  edit_format: diff
  use_repo_map: true
  overeager: false
  examples_as_sys_msg: true
  extra_params:
    extra_headers:
      Model: Qwen/Qwen3-30B-A3B-FP8
    temperature: 0.7
    top_p: 0.8
    top_k: 20
    presence_penalty: 1.5
    chat_template_kwargs:
      enable_thinking: false

- name: openai/qwen3:235b-a22b
  weak_model_name: openai/qwen3:30b-a3b-no-think
  edit_format: diff
  use_repo_map: true
  overeager: false
  examples_as_sys_msg: true
  extra_params:
    extra_headers:
      Model: Qwen/Qwen3-235B-A22B-FP8
    temperature: 0.6
    top_p: 0.95
    top_k: 20
    presence_penalty: 1.5

- name: openai/qwen3:235b-a22b-no-think
  weak_model_name: openai/qwen3:30b-a3b-no-think
  edit_format: diff
  use_repo_map: true
  overeager: false
  examples_as_sys_msg: true
  extra_params:
    extra_headers:
      Model: Qwen/Qwen3-235B-A22B-FP8
    temperature: 0.7
    top_p: 0.8
    top_k: 20
    presence_penalty: 1.5
    chat_template_kwargs:
      enable_thinking: false
