prSections:
- title: Needs My Review
  filters: is:open review-requested:@me
  type: null
- title: My Pull Requests
  filters: is:open author:@me
  type: null
issuesSections:
- title: Assigned
  filters: is:open assignee:@me
- title: My Issues
  filters: is:open author:@me
repo:
  branchesRefetchIntervalSeconds: 10
  prsRefetchIntervalSeconds: 10
defaults:
  preview:
    open: true
    width: 50
  prsLimit: 5
  issuesLimit: 5
  view: prs
  layout:
    prs:
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 20
      author:
        width: 15
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 15
    issues:
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 15
      creator:
        width: 10
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 10
keybindings:
  prs:
    - key: c
      command: >
        tmux new-window -c {{.RepoPath}} '
          gh pr checkout {{.PrNumber}} &&
          nvim -c ":Octo pr edit {{.PrNumber}}"
        '
  universal: []
  issues: []
  branches: []
repoPaths:
  infinity-microsoft/*: ~/work/*
  mentallyanimated/*: ~/mentallyanimated/*
theme:
  ui:
    sectionsShowCount: true
    table:
      showSeparator: true
      compact: false
pager:
  diff: ""
confirmQuit: false
