#!/bin/bash

find_root() {
  while [[ $PWD != '/' && ! -e .git ]];
  do
    cd ..
  done

  if [ "`pwd`" = '/' ];
  then
    echo "No .git repo was found"
    exit 1
  fi
}

check_rg_installed() {
  command -v rg >/dev/null 2>&1
}

find_in_current_repo() {
  check_rg_installed
  if [ $? = 0 ];
  then
    rg -e "import .*\\.$1;" --no-filename --no-heading -N --no-messages | \
      sort | uniq -c | sort -nr | head -n1 | tr -s ' ' | cut -d ' ' -f 3-
  else
    grep "import .*\\.$1;" -Rh | sort | uniq -c | sort -nr | head -n1 | \
      tr -s ' ' | cut -d ' ' -f 3-
  fi
}

find_in_gradle_cache() {
  check_rg_installed
  if [ $? = 0 ];
  then
    rg -e "import .*\\.$1;" ~/.gradle --no-filename --no-heading -N \
      --no-messages --text | sort | uniq -c | sort -nr | head -n1 | \
      tr -s ' ' | cut -d ' ' -f 3-
  else
    grep "import .*\\.$1;" ~/.gradle -Rah | sort | uniq -c | sort -nr | \
      head -n1 | tr -s ' ' | cut -d ' ' -f 3-
  fi
}

find_root
output="`find_in_current_repo $1`"
if [ -z "$output" ]
then
  output="`find_in_gradle_cache $1`"
fi
if [ -z "$output" ]
then
  output="// No import was found"
fi
echo $output
